sudo: required
services:
  - docker
before_install:
  - docker build -t svathsan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true svathsan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react-aws"
  env: "DockerReactAws-env"
  bucket_name: "elasticbeanstalk-ap-south-1-144357712367"
  bucket_path: "docker-react-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
